-- SkinQuest existing-database upgrade: v14.5.2 -> v14.5.3
-- Back up the database, then run this file once in Supabase SQL Editor.
-- Do not run the full-setup file on an existing project.

begin;

-- Promo redemption snapshots let an owner remove a code without erasing who
-- redeemed it or how many coins were awarded.
alter table public.sq_promo_redemptions
  add column if not exists id bigint generated by default as identity;
alter table public.sq_promo_redemptions
  add column if not exists code_snapshot text;
alter table public.sq_promo_redemptions
  add column if not exists campaign_snapshot text;

update public.sq_promo_redemptions pr
set code_snapshot = coalesce(pr.code_snapshot, pc.code),
    campaign_snapshot = coalesce(pr.campaign_snapshot, pc.campaign)
from public.sq_promo_codes pc
where pc.id = pr.promo_code_id
  and (pr.code_snapshot is null or pr.campaign_snapshot is null);

alter table public.sq_promo_redemptions
  drop constraint if exists sq_promo_redemptions_pkey;
alter table public.sq_promo_redemptions
  drop constraint if exists sq_promo_redemptions_promo_code_id_fkey;
alter table public.sq_promo_redemptions
  alter column promo_code_id drop not null;
alter table public.sq_promo_redemptions
  add constraint sq_promo_redemptions_pkey primary key (id);
alter table public.sq_promo_redemptions
  add constraint sq_promo_redemptions_promo_code_id_fkey
  foreign key (promo_code_id) references public.sq_promo_codes(id) on delete set null;
create unique index if not exists sq_promo_redemptions_live_user_idx
  on public.sq_promo_redemptions(promo_code_id, user_id)
  where promo_code_id is not null;
create index if not exists sq_promo_redemptions_code_snapshot_idx
  on public.sq_promo_redemptions(upper(code_snapshot), user_id)
  where code_snapshot is not null;

create or replace function public.sq_snapshot_promo_redemption()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.promo_code_id is not null then
    select coalesce(new.code_snapshot, pc.code),
           coalesce(new.campaign_snapshot, pc.campaign)
    into new.code_snapshot, new.campaign_snapshot
    from public.sq_promo_codes pc
    where pc.id = new.promo_code_id;
  end if;
  return new;
end;
$$;

revoke all on function public.sq_snapshot_promo_redemption() from public, anon, authenticated;
drop trigger if exists sq_promo_redemption_snapshot on public.sq_promo_redemptions;
create trigger sq_promo_redemption_snapshot
before insert on public.sq_promo_redemptions
for each row execute function public.sq_snapshot_promo_redemption();

-- fulfillment_mode now describes whether an item can still be ordered after
create or replace function public.sq_validate_reward_inventory()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(new.quantity_total,0)<0 or coalesce(new.quantity_reserved,0)<0 then
    raise exception 'Stock cannot be negative.';
  end if;
  if coalesce(new.quantity_reserved,0)>coalesce(new.quantity_total,0) then
    raise exception 'Reserved stock cannot be higher than total stock.';
  end if;
  -- Changing the fallback does not change existing order fulfilment snapshots.
  return new;
end;
$$;

create or replace function public.sq_notify_restock()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(old.quantity_total,0)-coalesce(old.quantity_reserved,0)<=0
     and coalesce(new.quantity_total,0)-coalesce(new.quantity_reserved,0)>0
     and coalesce(new.active,false) then
    insert into public.sq_notifications(user_id,notification_type,title,body,href,metadata)
    select s.user_id,'stock','Goal reward is back',
      coalesce(new.name,'A reward')||' is back in stock.',
      '/rewards?reward='||new.id,jsonb_build_object('reward_id',new.id)
    from public.sq_reward_stock_subscriptions s where s.reward_id=new.id;
    delete from public.sq_reward_stock_subscriptions where reward_id=new.id;
  end if;
  return new;
end;
$$;

-- fulfillment_mode now describes whether an item can still be ordered after
-- prepared stock reaches zero. Available stock is always used first.
create or replace function public.sq_reward_effective_fulfillment(
  p_fulfillment_mode text,
  p_quantity_total integer,
  p_quantity_reserved integer
)
returns text
language sql
immutable
as $$
  select case
    when greatest(0, coalesce(p_quantity_total, 0) - coalesce(p_quantity_reserved, 0)) > 0 then 'stocked'
    when p_fulfillment_mode = 'orderable' then 'orderable'
    else 'stocked'
  end;
$$;

revoke all on function public.sq_reward_effective_fulfillment(text,integer,integer) from public;
grant execute on function public.sq_reward_effective_fulfillment(text,integer,integer) to anon, authenticated, service_role;

create or replace function public.redeem_reward(p_reward_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_user_id uuid := auth.uid();
  v_profile public.profiles%rowtype;
  v_reward public.reward_items%rowtype;
  v_cost integer;
  v_available integer;
  v_request_id bigint;
  v_order_number text;
  v_user_redemptions integer;
  v_auth_email text;
  v_partner text;
  v_mode text;
  v_status text;
  v_estimated_ready_at timestamptz;
begin
  if v_user_id is null then raise exception 'You must be logged in.'; end if;
  perform public.ensure_skinquest_profile();
  select * into v_profile from public.profiles where id = v_user_id for update;
  if coalesce(v_profile.account_status, 'active') <> 'active' then raise exception 'Account is not active.'; end if;

  select lower(coalesce(email, '')) into v_auth_email from auth.users where id = v_user_id;
  if (v_auth_email = '' or v_auth_email like '%@steam.skinquestcs.com') and
     (nullif(trim(coalesce(v_profile.contact_email, '')), '') is null or v_profile.contact_email_verified_at is null) then
    raise exception 'Verified contact email required.';
  end if;
  if nullif(trim(coalesce(v_profile.steam_trade_url, '')), '') is null then raise exception 'Steam trade URL is required.'; end if;
  if v_profile.steam_trade_url !~* '^https://(www\.)?steamcommunity\.com/tradeoffer/new/?\?' or
     v_profile.steam_trade_url !~ '(^|[?&])partner=[0-9]+(&|$)' or
     v_profile.steam_trade_url !~ '(^|[?&])token=[A-Za-z0-9_-]+(&|$)' then
    raise exception 'Steam trade URL is invalid.';
  end if;
  if v_profile.steam_id ~ '^[0-9]+$' then
    v_partner := substring(v_profile.steam_trade_url from '[?&]partner=([0-9]+)');
    if v_partner is null or v_partner::numeric <> (v_profile.steam_id::numeric - 76561197960265728::numeric) then
      raise exception 'Steam trade URL belongs to a different connected Steam account.';
    end if;
  end if;

  select * into v_reward from public.reward_items where id = p_reward_id and active = true for update;
  if not found then raise exception 'Reward not found.'; end if;
  v_cost := coalesce(nullif(v_reward.points_coins, 0), v_reward.points_cost, 0);
  if v_cost <= 0 then raise exception 'Reward price is invalid.'; end if;

  v_available := greatest(0, coalesce(v_reward.quantity_total, 0) - coalesce(v_reward.quantity_reserved, 0));
  v_mode := public.sq_reward_effective_fulfillment(
    v_reward.fulfillment_mode, v_reward.quantity_total, v_reward.quantity_reserved
  );
  if v_mode = 'stocked' then
    if v_available <= 0 then raise exception 'Reward is out of stock.'; end if;
    v_status := 'ready_to_trade';
    v_estimated_ready_at := now() + interval '2 days';
  else
    v_status := 'ordered';
    v_estimated_ready_at := now() + make_interval(days => greatest(7, least(coalesce(v_reward.order_eta_days, 8), 30)));
  end if;

  if v_reward.max_per_user is not null then
    select count(*) into v_user_redemptions
    from public.redemption_requests
    where user_id = v_user_id and reward_id = v_reward.id
      and status not in ('rejected', 'refunded', 'cancelled');
    if v_user_redemptions >= v_reward.max_per_user then
      raise exception 'You have reached the redemption limit for this reward.';
    end if;
  end if;
  if coalesce(v_profile.points_balance, 0) < v_cost then raise exception 'Not enough coins.'; end if;

  update public.profiles
  set points_balance = points_balance - v_cost, updated_at = now()
  where id = v_user_id;

  if v_mode = 'stocked' then
    update public.reward_items
    set quantity_reserved = coalesce(quantity_reserved, 0) + 1, updated_at = now()
    where id = v_reward.id;
  end if;

  insert into public.redemption_requests (
    user_id, reward_id, reward_name, points_coins, points_cost, steam_trade_url,
    status, fulfillment_mode, estimated_ready_at, ready_at
  ) values (
    v_user_id, v_reward.id, v_reward.name, v_cost, v_cost, v_profile.steam_trade_url,
    v_status, v_mode, v_estimated_ready_at,
    case when v_status = 'ready_to_trade' then now() else null end
  ) returning id, order_number into v_request_id, v_order_number;

  insert into public.coin_adjustments(user_id, amount, reason, source_type, source_id, metadata)
  values(
    v_user_id, -v_cost,
    case when v_mode = 'orderable' then 'Reward order / ' else 'Redeem hold / ' end || v_reward.name,
    case when v_mode = 'orderable' then 'reward_order' else 'redemption_hold' end,
    v_request_id::text,
    jsonb_build_object('reward_id',v_reward.id,'reward_name',v_reward.name,'fulfillment_mode',v_mode,'status',v_status)
  );

  return jsonb_build_object(
    'ok',true,'request_id',v_request_id,'order_number',v_order_number,
    'fulfillment_mode',v_mode,'status',v_status,'estimated_ready_at',v_estimated_ready_at
  );
end;
$$;

revoke all on function public.redeem_reward(bigint) from public, anon;
grant execute on function public.redeem_reward(bigint) to authenticated;

create or replace function public.sq_search_rewards(
  p_query text default null,
  p_min_coins integer default null,
  p_max_coins integer default null,
  p_availability text default 'all',
  p_balance integer default 0,
  p_sort text default 'price-desc',
  p_show_out_of_stock boolean default true,
  p_limit integer default 48,
  p_offset integer default 0
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_query text := left(lower(trim(coalesce(p_query, ''))), 120);
  v_availability text := lower(coalesce(p_availability, 'all'));
  v_sort text := lower(coalesce(p_sort, 'price-desc'));
  v_limit integer := greatest(1, least(coalesce(p_limit, 48), 60));
  v_offset integer := greatest(0, coalesce(p_offset, 0));
begin
  if v_availability not in ('all','affordable','in-stock','orderable') then v_availability := 'all'; end if;
  if v_sort not in ('price-asc','price-desc','featured','stock-desc','name-asc') then v_sort := 'price-desc'; end if;

  return (
    with filtered as (
      select r.*,
        greatest(0, coalesce(r.quantity_total,0) - coalesce(r.quantity_reserved,0)) as sq_available_stock,
        public.sq_reward_effective_fulfillment(r.fulfillment_mode,r.quantity_total,r.quantity_reserved) as sq_current_fulfillment,
        case when greatest(0,coalesce(r.quantity_total,0)-coalesce(r.quantity_reserved,0)) <= 0
                   and r.fulfillment_mode <> 'orderable' then 1 else 0 end as sq_out_of_stock
      from public.reward_items r
      where r.active = true
        and (
          v_query = '' or lower(coalesce(r.name,'')) like '%' || v_query || '%'
          or lower(coalesce(r.market_name,'')) like '%' || v_query || '%'
          or lower(coalesce(r.description,'')) like '%' || v_query || '%'
          or lower(coalesce(r.rarity,'')) like '%' || v_query || '%'
          or lower(coalesce(r.condition,'')) like '%' || v_query || '%'
        )
        and (p_min_coins is null or r.points_coins >= greatest(0,p_min_coins))
        and (p_max_coins is null or r.points_coins <= greatest(0,p_max_coins))
        and (
          coalesce(p_show_out_of_stock,true)
          or r.fulfillment_mode = 'orderable'
          or greatest(0,coalesce(r.quantity_total,0)-coalesce(r.quantity_reserved,0)) > 0
        )
        and (
          v_availability = 'all'
          or (v_availability = 'affordable'
              and r.points_coins <= greatest(0,coalesce(p_balance,0))
              and (r.fulfillment_mode = 'orderable'
                   or greatest(0,coalesce(r.quantity_total,0)-coalesce(r.quantity_reserved,0)) > 0))
          or (v_availability = 'in-stock'
              and greatest(0,coalesce(r.quantity_total,0)-coalesce(r.quantity_reserved,0)) > 0)
          or (v_availability = 'orderable'
              and r.fulfillment_mode = 'orderable'
              and greatest(0,coalesce(r.quantity_total,0)-coalesce(r.quantity_reserved,0)) <= 0)
        )
    ), ordered as (
      select f.*, row_number() over (order by
        f.sq_out_of_stock asc,
        case when v_sort = 'price-asc' then f.points_coins end asc nulls last,
        case when v_sort = 'price-desc' then f.points_coins end desc nulls last,
        case when v_sort = 'stock-desc' then f.sq_available_stock end desc nulls last,
        case when v_sort = 'featured' then f.sort_order end asc nulls last,
        case when v_sort = 'name-asc' then lower(f.name) end asc nulls last,
        lower(f.name) asc, f.id asc
      ) as sq_row_number
      from filtered f
    ), page as (
      select * from ordered
      where sq_row_number > v_offset and sq_row_number <= v_offset + v_limit
    )
    select jsonb_build_object(
      'items', coalesce((
        select jsonb_agg(
          (to_jsonb(p)-'sq_row_number'-'sq_available_stock'-'sq_out_of_stock'-'sq_current_fulfillment')
          || jsonb_build_object(
            'available_stock',p.sq_available_stock,
            'current_fulfillment',p.sq_current_fulfillment,
            'price_is_current',p.pricing_mode <> 'steam' or (
              coalesce(p.steam_price_minor,0) > 0
              and p.steam_price_valid_until is not null
              and p.steam_price_valid_until > now()
            )
          ) order by p.sq_row_number
        ) from page p
      ), '[]'::jsonb),
      'total',(select count(*) from filtered),'limit',v_limit,'offset',v_offset
    )
  );
end;
$$;

revoke all on function public.sq_search_rewards(text,integer,integer,text,integer,text,boolean,integer,integer) from public;
grant execute on function public.sq_search_rewards(text,integer,integer,text,integer,text,boolean,integer,integer) to anon, authenticated;

drop function if exists public.sq_admin_search_reward_items(text,text,integer,integer);
create function public.sq_admin_search_reward_items(
  p_query text default null,
  p_filter text default 'all',
  p_sort text default 'stock-first',
  p_limit integer default 75,
  p_offset integer default 0
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_query text := left(lower(trim(coalesce(p_query,''))),120);
  v_filter text := lower(coalesce(p_filter,'all'));
  v_sort text := lower(coalesce(p_sort,'stock-first'));
  v_limit integer := greatest(1,least(coalesce(p_limit,75),150));
  v_offset integer := greatest(0,coalesce(p_offset,0));
begin
  if not public.is_admin() then raise exception 'Admin access required.'; end if;
  if v_filter not in ('all','stocked','orderable','steam','stale','inactive') then v_filter := 'all'; end if;
  if v_sort not in ('stock-first','order-first','name-asc','price-asc','price-desc') then v_sort := 'stock-first'; end if;

  return (
    with filtered as (
      select r.*,
        greatest(0,coalesce(r.quantity_total,0)-coalesce(r.quantity_reserved,0)) as sq_available_stock,
        public.sq_reward_effective_fulfillment(r.fulfillment_mode,r.quantity_total,r.quantity_reserved) as sq_current_fulfillment
      from public.reward_items r
      where (
        v_query = '' or lower(coalesce(r.name,'')) like '%' || v_query || '%'
        or lower(coalesce(r.market_name,'')) like '%' || v_query || '%'
        or lower(coalesce(r.rarity,'')) like '%' || v_query || '%'
        or lower(coalesce(r.condition,'')) like '%' || v_query || '%'
      )
      and (
        v_filter = 'all'
        or (v_filter = 'stocked' and greatest(0,coalesce(r.quantity_total,0)-coalesce(r.quantity_reserved,0)) > 0)
        or (v_filter = 'orderable' and r.fulfillment_mode = 'orderable'
            and greatest(0,coalesce(r.quantity_total,0)-coalesce(r.quantity_reserved,0)) <= 0)
        or (v_filter = 'steam' and r.pricing_mode = 'steam')
        or (v_filter = 'stale' and r.pricing_mode = 'steam' and (
          coalesce(r.steam_price_minor,0) <= 0 or r.steam_price_valid_until is null or r.steam_price_valid_until <= now()
        ))
        or (v_filter = 'inactive' and r.active = false)
      )
    ), ordered as (
      select f.*, row_number() over (order by
        f.active desc,
        case when v_sort = 'stock-first' then case when f.sq_available_stock > 0 then 0 else 1 end end asc nulls last,
        case when v_sort = 'order-first' then case when f.sq_current_fulfillment = 'orderable' then 0 else 1 end end asc nulls last,
        case when v_sort = 'name-asc' then lower(f.name) end asc nulls last,
        case when v_sort = 'price-asc' then f.points_coins end asc nulls last,
        case when v_sort = 'price-desc' then f.points_coins end desc nulls last,
        f.sort_order asc, lower(f.name) asc, f.id asc
      ) as sq_row_number
      from filtered f
    ), page as (
      select * from ordered
      where sq_row_number > v_offset and sq_row_number <= v_offset + v_limit
    )
    select jsonb_build_object(
      'items',coalesce((
        select jsonb_agg(
          (to_jsonb(p)-'sq_row_number'-'sq_available_stock'-'sq_current_fulfillment')
          || jsonb_build_object('available_stock',p.sq_available_stock,'current_fulfillment',p.sq_current_fulfillment)
          order by p.sq_row_number
        ) from page p
      ),'[]'::jsonb),
      'total',(select count(*) from filtered),'limit',v_limit,'offset',v_offset
    )
  );
end;
$$;

revoke all on function public.sq_admin_search_reward_items(text,text,text,integer,integer) from public, anon, authenticated;
grant execute on function public.sq_admin_search_reward_items(text,text,text,integer,integer) to authenticated;

create or replace function public.sq_admin_reward_pricing_dashboard()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'Admin access required.'; end if;
  return jsonb_build_object(
    'settings',coalesce((select to_jsonb(s) from public.sq_reward_pricing_settings s where id=1),'{}'::jsonb),
    'sync',coalesce((select to_jsonb(c) from public.sq_steam_catalog_sync_state c where id=1),'{}'::jsonb),
    'stats',jsonb_build_object(
      'active_listings',(select count(*) from public.reward_items where active=true),
      'orderable_listings',(select count(*) from public.reward_items where active=true and fulfillment_mode='orderable'
        and greatest(0,coalesce(quantity_total,0)-coalesce(quantity_reserved,0))<=0),
      'prepared_units',(select coalesce(sum(greatest(0,quantity_total-quantity_reserved)),0) from public.reward_items),
      'reserved_units',(select coalesce(sum(greatest(0,quantity_reserved)),0) from public.reward_items),
      'steam_linked',(select count(*) from public.reward_items where pricing_mode='steam'),
      'stale_prices',(select count(*) from public.reward_items where active=true and pricing_mode='steam' and (
        coalesce(steam_price_minor,0)<=0 or steam_price_valid_until is null or steam_price_valid_until<=now()
      )),
      'catalog_items',(select count(*) from public.reward_items where catalog_managed=true)
    )
  );
end;
$$;

revoke all on function public.sq_admin_reward_pricing_dashboard() from public, anon, authenticated;
grant execute on function public.sq_admin_reward_pricing_dashboard() to authenticated;

-- New custom rewards use an RPC so an exact existing Steam/name match cannot
-- silently create a duplicate listing.
create or replace function public.sq_owner_create_manual_reward(p_reward jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text := left(trim(coalesce(p_reward->>'name','')),240);
  v_market_name text := nullif(left(trim(coalesce(p_reward->>'market_name','')),240),'');
  v_existing_id bigint;
  v_id bigint;
  v_points integer;
  v_total integer;
  v_reserved integer;
  v_eta integer;
  v_sort integer;
  v_max integer;
  v_fulfillment text;
begin
  if not public.is_owner() then raise exception 'Owner access required.'; end if;
  if v_name = '' then raise exception 'Reward name is required.'; end if;

  select r.id into v_existing_id
  from public.reward_items r
  where (v_market_name is not null and lower(coalesce(r.market_name,''))=lower(v_market_name))
     or lower(trim(r.name))=lower(v_name)
  order by case when v_market_name is not null and lower(coalesce(r.market_name,''))=lower(v_market_name) then 0 else 1 end, r.id
  limit 1;
  if v_existing_id is not null then
    return jsonb_build_object('ok',true,'existing',true,'id',v_existing_id,'name',
      (select name from public.reward_items where id=v_existing_id));
  end if;

  begin
    v_points := (p_reward->>'points_coins')::integer;
    v_total := coalesce((p_reward->>'quantity_total')::integer,0);
    v_reserved := coalesce((p_reward->>'quantity_reserved')::integer,0);
    v_eta := coalesce((p_reward->>'order_eta_days')::integer,8);
    v_sort := coalesce((p_reward->>'sort_order')::integer,0);
    v_max := nullif(p_reward->>'max_per_user','')::integer;
  exception when invalid_text_representation or numeric_value_out_of_range then
    raise exception 'Reward numbers are invalid.';
  end;
  v_fulfillment := case when p_reward->>'fulfillment_mode'='orderable' then 'orderable' else 'stocked' end;
  if v_points < 1 then raise exception 'Coin price must be at least 1.'; end if;
  if v_total < 0 or v_reserved < 0 or v_reserved > v_total then raise exception 'Reserved stock must be between 0 and total stock.'; end if;
  if v_eta < 7 or v_eta > 30 then raise exception 'Order ETA must be between 7 and 30 days.'; end if;
  if v_max is not null and v_max < 1 then raise exception 'User limit must be above 0.'; end if;

  insert into public.reward_items(
    name,market_name,description,image_url,rarity,condition,
    points_coins,points_cost,quantity_total,quantity_reserved,
    active,sort_order,max_per_user,fulfillment_mode,order_eta_days,
    pricing_mode,manual_price_override,catalog_managed
  ) values(
    v_name,v_market_name,nullif(left(trim(coalesce(p_reward->>'description','')),500),''),
    nullif(left(trim(coalesce(p_reward->>'image_url','')),500),''),
    nullif(left(lower(trim(coalesce(p_reward->>'rarity',''))),40),''),
    nullif(left(trim(coalesce(p_reward->>'condition','')),40),''),
    v_points,v_points,v_total,v_reserved,
    coalesce((p_reward->>'active')::boolean,true),v_sort,v_max,v_fulfillment,v_eta,
    'manual',true,false
  ) returning id into v_id;
  return jsonb_build_object('ok',true,'existing',false,'id',v_id,'name',v_name);
end;
$$;

revoke all on function public.sq_owner_create_manual_reward(jsonb) from public, anon, authenticated;
grant execute on function public.sq_owner_create_manual_reward(jsonb) to authenticated;

create or replace function public.sq_owner_delete_manual_reward(p_reward_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_reward public.reward_items%rowtype;
begin
  if not public.is_owner() then raise exception 'Owner access required.'; end if;
  select * into v_reward from public.reward_items where id=p_reward_id for update;
  if not found then raise exception 'Reward not found.'; end if;
  if coalesce(v_reward.catalog_managed,false) then
    raise exception 'Steam-managed rewards return on the next sync. Hide them instead.';
  end if;
  if coalesce(v_reward.quantity_reserved,0)>0 or exists(
    select 1 from public.redemption_requests
    where reward_id=p_reward_id
      and status not in ('completed','rejected','refunded','cancelled')
  ) then
    raise exception 'Finish or cancel this reward''s open orders before deleting it.';
  end if;

  delete from public.reward_items where id=p_reward_id;
  -- Existing order rows keep reward_name and coin snapshots; the FK sets
  -- reward_id to NULL and the UI labels those rows as deleted items.
  return jsonb_build_object('ok',true,'reward_id',p_reward_id,'name',v_reward.name);
end;
$$;

revoke all on function public.sq_owner_delete_manual_reward(bigint) from public, anon, authenticated;
grant execute on function public.sq_owner_delete_manual_reward(bigint) to authenticated;

create or replace function public.sq_owner_set_promo_active(p_promo_id bigint,p_active boolean)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_promo public.sq_promo_codes%rowtype;
begin
  if not public.is_owner() then raise exception 'Owner access required.'; end if;
  update public.sq_promo_codes
  set active=coalesce(p_active,false)
  where id=p_promo_id
  returning * into v_promo;
  if not found then raise exception 'Promo code not found.'; end if;
  insert into public.sq_admin_audit_log(actor_user_id,action,entity_type,entity_id,details)
  values(auth.uid(),'promo_status_update','promo_code',p_promo_id::text,
    jsonb_build_object('code',v_promo.code,'active',v_promo.active));
  return jsonb_build_object('ok',true,'id',v_promo.id,'code',v_promo.code,'active',v_promo.active);
end;
$$;

revoke all on function public.sq_owner_set_promo_active(bigint,boolean) from public, anon, authenticated;
grant execute on function public.sq_owner_set_promo_active(bigint,boolean) to authenticated;

create or replace function public.sq_owner_delete_promo_code(p_promo_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_promo public.sq_promo_codes%rowtype;
begin
  if not public.is_owner() then raise exception 'Owner access required.'; end if;
  select * into v_promo from public.sq_promo_codes where id=p_promo_id for update;
  if not found then raise exception 'Promo code not found.'; end if;
  delete from public.sq_promo_codes where id=p_promo_id;
  insert into public.sq_admin_audit_log(actor_user_id,action,entity_type,entity_id,details)
  values(auth.uid(),'promo_delete','promo_code',p_promo_id::text,
    jsonb_build_object('code',v_promo.code,'campaign',v_promo.campaign,'redemptions',v_promo.redemptions_count));
  return jsonb_build_object('ok',true,'promo_id',p_promo_id,'code',v_promo.code,
    'preserved_redemptions',coalesce(v_promo.redemptions_count,0));
end;
$$;

revoke all on function public.sq_owner_delete_promo_code(bigint) from public, anon, authenticated;
grant execute on function public.sq_owner_delete_promo_code(bigint) to authenticated;

create or replace function public.sq_admin_search_promo_codes(
  p_query text default null,
  p_state text default 'all',
  p_limit integer default 100,
  p_offset integer default 0
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_query text := left(lower(trim(coalesce(p_query,''))),120);
  v_state text := lower(coalesce(p_state,'all'));
  v_limit integer := greatest(1,least(coalesce(p_limit,100),200));
  v_offset integer := greatest(0,coalesce(p_offset,0));
begin
  if not public.is_admin() then raise exception 'Admin access required.'; end if;
  if v_state not in ('all','active','inactive') then v_state := 'all'; end if;
  return (
    with filtered as (
      select p.*
      from public.sq_promo_codes p
      where (v_query='' or lower(p.code) like '%'||v_query||'%'
        or lower(coalesce(p.campaign,'')) like '%'||v_query||'%')
        and (
          v_state='all'
          or (v_state='active' and p.active=true
            and (p.starts_at is null or p.starts_at<=now())
            and (p.ends_at is null or p.ends_at>now())
            and (p.max_redemptions is null or p.redemptions_count<p.max_redemptions))
          or (v_state='inactive' and not (
            p.active=true
            and (p.starts_at is null or p.starts_at<=now())
            and (p.ends_at is null or p.ends_at>now())
            and (p.max_redemptions is null or p.redemptions_count<p.max_redemptions)
          ))
        )
    ), page as (
      select * from filtered order by created_at desc,id desc limit v_limit offset v_offset
    )
    select jsonb_build_object(
      'items',coalesce((select jsonb_agg(to_jsonb(p) order by p.created_at desc,p.id desc) from page p),'[]'::jsonb),
      'total',(select count(*) from filtered),'limit',v_limit,'offset',v_offset
    )
  );
end;
$$;

revoke all on function public.sq_admin_search_promo_codes(text,text,integer,integer) from public, anon, authenticated;
grant execute on function public.sq_admin_search_promo_codes(text,text,integer,integer) to authenticated;

create or replace function public.sq_redeem_promo_code(p_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_code text := upper(btrim(coalesce(p_code,'')));
  v_promo public.sq_promo_codes%rowtype;
begin
  if v_user is null then raise exception 'Sign in required.'; end if;
  if length(v_code)<3 then raise exception 'Enter a valid code.'; end if;
  select * into v_promo from public.sq_promo_codes where upper(code)=v_code for update;
  if not found then raise exception 'That code does not exist.'; end if;
  if not v_promo.active then raise exception 'That code is inactive.'; end if;
  if v_promo.starts_at is not null and now()<v_promo.starts_at then raise exception 'That code is not active yet.'; end if;
  if v_promo.ends_at is not null and now()>=v_promo.ends_at then raise exception 'That code has expired.'; end if;
  if v_promo.max_redemptions is not null and v_promo.redemptions_count>=v_promo.max_redemptions then
    raise exception 'That code has reached its redemption limit.';
  end if;
  if exists(
    select 1 from public.sq_promo_redemptions
    where user_id=v_user and (
      promo_code_id=v_promo.id or upper(coalesce(code_snapshot,''))=v_code
    )
  ) then raise exception 'You have already redeemed that code.'; end if;

  perform 1 from public.profiles where id=v_user for update;
  if not found then raise exception 'Profile not found.'; end if;
  insert into public.sq_promo_redemptions(
    promo_code_id,user_id,coins_awarded,code_snapshot,campaign_snapshot
  ) values(v_promo.id,v_user,v_promo.coin_amount,v_promo.code,v_promo.campaign);
  update public.sq_promo_codes set redemptions_count=redemptions_count+1 where id=v_promo.id;
  update public.profiles set points_balance=coalesce(points_balance,0)+v_promo.coin_amount where id=v_user;
  insert into public.coin_adjustments(user_id,amount,reason)
  values(v_user,v_promo.coin_amount,'Promo code: '||v_promo.code);
  insert into public.sq_product_events(user_id,event_name,page_path,properties)
  values(v_user,'promo_redeemed',null,jsonb_build_object('campaign',v_promo.campaign,'coins',v_promo.coin_amount));
  return jsonb_build_object('ok',true,'coins_awarded',v_promo.coin_amount,'campaign',v_promo.campaign);
end;
$$;

revoke all on function public.sq_redeem_promo_code(text) from public;
grant execute on function public.sq_redeem_promo_code(text) to authenticated;

create or replace function public.sq_admin_create_promo_code(
  p_code text,
  p_coin_amount integer,
  p_campaign text default null,
  p_max_redemptions integer default null,
  p_starts_at timestamptz default null,
  p_ends_at timestamptz default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code text := upper(regexp_replace(btrim(coalesce(p_code,'')),'[^A-Za-z0-9_-]+','','g'));
  v_id bigint;
begin
  if not public.sq_is_admin() then raise exception 'Admin access required.'; end if;
  if length(v_code)<3 then raise exception 'Code must contain at least 3 valid characters.'; end if;
  if p_coin_amount<=0 or p_coin_amount>100000 then raise exception 'Coin amount is outside the allowed range.'; end if;
  if p_max_redemptions is not null and p_max_redemptions<=0 then raise exception 'Max redemptions must be positive.'; end if;
  if p_ends_at is not null and p_starts_at is not null and p_ends_at<=p_starts_at then raise exception 'End must be after start.'; end if;
  if exists(select 1 from public.sq_promo_redemptions where upper(coalesce(code_snapshot,''))=v_code) then
    raise exception 'That code was used before and cannot be recreated after deletion.';
  end if;
  insert into public.sq_promo_codes(code,campaign,coin_amount,max_redemptions,starts_at,ends_at,created_by)
  values(v_code,nullif(btrim(p_campaign),''),p_coin_amount,p_max_redemptions,p_starts_at,p_ends_at,auth.uid())
  returning id into v_id;
  insert into public.sq_admin_audit_log(actor_user_id,action,entity_type,entity_id,details)
  values(auth.uid(),'promo_create','promo_code',v_id::text,
    jsonb_build_object('code',v_code,'coins',p_coin_amount,'max',p_max_redemptions,'campaign',p_campaign));
  return jsonb_build_object('ok',true,'id',v_id,'code',v_code);
end;
$$;

revoke all on function public.sq_admin_create_promo_code(text,integer,text,integer,timestamptz,timestamptz) from public;
grant execute on function public.sq_admin_create_promo_code(text,integer,text,integer,timestamptz,timestamptz) to authenticated;

commit;
notify pgrst, 'reload schema';
